/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;
import CONTROLADOR.ControladorAgendaDeCitasAsignadas; 


public class frmAgendadeCitasAsignadas extends javax.swing.JInternalFrame {

    public frmAgendadeCitasAsignadas() {
        initComponents();
        ControladorAgendaDeCitasAsignadas ctrl = new ControladorAgendaDeCitasAsignadas();
        ctrl.cargarTabla(tblAgendaDeCitas);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCitasAsignadas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgendaDeCitas = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCitasAsignadas.setBackground(new java.awt.Color(0, 255, 51));
        pnlCitasAsignadas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAgendaDeCitas.setBackground(new java.awt.Color(0, 153, 0));
        tblAgendaDeCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblAgendaDeCitas);

        pnlCitasAsignadas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 990, 570));

        getContentPane().add(pnlCitasAsignadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel pnlCitasAsignadas;
    public javax.swing.JTable tblAgendaDeCitas;
    // End of variables declaration//GEN-END:variables
}
