/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author James
 */
public class frmAgregarMascotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarMascotas
     */
    public frmAgregarMascotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDniClie2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreMascota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jdcFechaNaci = new com.toedter.calendar.JCalendar();
        jLabel4 = new javax.swing.JLabel();
        txtRazaMascota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxEspecieMascota = new javax.swing.JComboBox<>();
        btnRegistrarMas = new javax.swing.JButton();
        btnAgregarCita = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DNI Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtDniClie2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txtDniClie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Nombre mascota");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtNombreMascota.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txtNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 310, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Nacimiento mascota");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        jPanel1.add(jdcFechaNaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 310, 160));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Especie mascota");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        txtRazaMascota.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtRazaMascota.addActionListener(this::txtRazaMascotaActionPerformed);
        jPanel1.add(txtRazaMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 310, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Raza mascota");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        cbxEspecieMascota.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxEspecieMascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxEspecieMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 310, 60));

        btnRegistrarMas.setBackground(new java.awt.Color(51, 0, 51));
        btnRegistrarMas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistrarMas.setText("REGISTRAR MASCOTA");
        jPanel1.add(btnRegistrarMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 310, 70));

        btnAgregarCita.setBackground(new java.awt.Color(0, 0, 51));
        btnAgregarCita.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAgregarCita.setText("AGREGAR CITA");
        btnAgregarCita.setEnabled(false);
        jPanel1.add(btnAgregarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 310, 70));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Registrar Mascota");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRazaMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarCita;
    public javax.swing.JButton btnRegistrarMas;
    public javax.swing.JComboBox<String> cbxEspecieMascota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public com.toedter.calendar.JCalendar jdcFechaNaci;
    public javax.swing.JTextField txtDniClie2;
    public javax.swing.JTextField txtNombreMascota;
    public javax.swing.JTextField txtRazaMascota;
    // End of variables declaration//GEN-END:variables
}
