/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author pc
 */
public class frmAgregarEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAgregarEmpleados
     */
    public frmAgregarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContrato = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSegundoNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroDeTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbxTurno = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JComboBox<>();
        btnAgregarCredencial = new javax.swing.JButton();
        btnRegistrarEmpleado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstServicios = new javax.swing.JList<>();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContrato.setBackground(new java.awt.Color(0, 0, 0));
        pnlContrato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AGREGAR EMPLEADO");
        pnlContrato.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 250, 30));

        jLabel1.setText("DNI ");
        pnlContrato.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        pnlContrato.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 340, 60));

        jLabel3.setText("PRIMER NOMBRE");
        pnlContrato.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        pnlContrato.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 340, 60));

        jLabel4.setText("SEGUNDO NOMBRE");
        pnlContrato.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        pnlContrato.add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 340, 60));

        jLabel5.setText("APELLIDO PATERNO ");
        pnlContrato.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 30));
        pnlContrato.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 340, 60));

        jLabel6.setText("APELLIDO MATERNO");
        pnlContrato.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));
        pnlContrato.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 340, 60));

        jLabel7.setText("NUMERO DE TELEFONO");
        pnlContrato.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));
        pnlContrato.add(txtNumeroDeTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 320, 60));

        jLabel8.setText("TURNO");
        pnlContrato.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 150, 20));

        cbxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlContrato.add(cbxTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 320, 60));

        jLabel9.setText("PUESTO LABORAL");
        pnlContrato.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        txtPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlContrato.add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 320, 60));

        btnAgregarCredencial.setText("AGREGAR CREDENCIAL");
        pnlContrato.add(btnAgregarCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 270, 50));

        btnRegistrarEmpleado.setText("REGISTRAR EMPLEADO");
        pnlContrato.add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 270, 50));

        lstServicios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstServicios);

        pnlContrato.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 320, 100));

        getContentPane().add(pnlContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 830, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarCredencial;
    public javax.swing.JButton btnRegistrarEmpleado;
    public javax.swing.JComboBox<String> cbxTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList<String> lstServicios;
    public javax.swing.JPanel pnlContrato;
    public javax.swing.JTextField txtApellidoMaterno;
    public javax.swing.JTextField txtApellidoPaterno;
    public javax.swing.JTextField txtDni;
    public javax.swing.JTextField txtNumeroDeTelefono;
    public javax.swing.JTextField txtPrimerNombre;
    public javax.swing.JComboBox<String> txtPuesto;
    public javax.swing.JTextField txtSegundoNombre;
    // End of variables declaration//GEN-END:variables
}
