/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package VISTA;

/**
 *
 * @author pc
 */
public class frmCredenciales extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmCredenciales.class.getName());

    /**
     * Creates new form frmCredenciales
     */
    public frmCredenciales(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCredenciales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jpdContraseña = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cbxRol = new javax.swing.JComboBox<>();
        btnComfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCredenciales.setBackground(new java.awt.Color(51, 153, 255));
        pnlCredenciales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("INGRESE TUS CREDENCIALES");
        pnlCredenciales.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 290, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("USUARIO");
        pnlCredenciales.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 30));
        pnlCredenciales.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 320, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CONTRASEÑA");
        pnlCredenciales.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        pnlCredenciales.add(jpdContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 320, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ROL");
        pnlCredenciales.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, -1));

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlCredenciales.add(cbxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 320, 60));

        btnComfirmar.setBackground(new java.awt.Color(0, 51, 255));
        btnComfirmar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComfirmar.setForeground(new java.awt.Color(0, 0, 0));
        btnComfirmar.setText("COMFIRMAR");
        pnlCredenciales.add(btnComfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 150, 50));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("CANCELAR");
        pnlCredenciales.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 150, 50));

        getContentPane().add(pnlCredenciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                frmCredenciales dialog = new frmCredenciales(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnComfirmar;
    public javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPasswordField jpdContraseña;
    private javax.swing.JPanel pnlCredenciales;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
