/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author user
 */
public class frmGestionDeCitas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmGestionDeCitas
     */
    public frmGestionDeCitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGestionarCitas = new javax.swing.JPanel();
        cbxVeterinario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spnFecha = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMotivoDeCita = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cbxNombreMascota = new javax.swing.JComboBox<>();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxTipodeServicio = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlGestionarCitas.setBackground(new java.awt.Color(255, 255, 204));
        pnlGestionarCitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxVeterinario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxVeterinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlGestionarCitas.add(cbxVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 560, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Informacion de Cita");
        pnlGestionarCitas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mascota");
        pnlGestionarCitas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Veterinario");
        pnlGestionarCitas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Fecha");
        pnlGestionarCitas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        spnFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        spnFecha.setModel(new javax.swing.SpinnerDateModel());
        pnlGestionarCitas.add(spnFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 290, 70));

        txaMotivoDeCita.setColumns(20);
        txaMotivoDeCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txaMotivoDeCita.setLineWrap(true);
        txaMotivoDeCita.setRows(5);
        txaMotivoDeCita.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaMotivoDeCita);

        pnlGestionarCitas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 690, 150));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Estado");
        pnlGestionarCitas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Motivo de Cita");
        pnlGestionarCitas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 110, -1));

        btnNuevo.setBackground(new java.awt.Color(51, 204, 255));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevo.setText("NUEVO");
        pnlGestionarCitas.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 190, 60));

        btnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardar.setText("GUARDAR");
        pnlGestionarCitas.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 190, 60));

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setText("SALIR");
        pnlGestionarCitas.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 210, 60));

        cbxNombreMascota.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxNombreMascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlGestionarCitas.add(cbxNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 280, 70));

        cbxEstado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxEstado.addActionListener(this::cbxEstadoActionPerformed);
        pnlGestionarCitas.add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 290, 70));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tipo de Servicio");
        pnlGestionarCitas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        cbxTipodeServicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxTipodeServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlGestionarCitas.add(cbxTipodeServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 280, 70));

        getContentPane().add(pnlGestionarCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnSalir;
    public javax.swing.JComboBox<String> cbxEstado;
    public javax.swing.JComboBox<String> cbxNombreMascota;
    public javax.swing.JComboBox<String> cbxTipodeServicio;
    public javax.swing.JComboBox<String> cbxVeterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel pnlGestionarCitas;
    public javax.swing.JSpinner spnFecha;
    public javax.swing.JTextArea txaMotivoDeCita;
    // End of variables declaration//GEN-END:variables
}
