/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author James
 */
public class frmRegistrarClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRegistrarClientes
     */
    public frmRegistrarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDniClie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreClie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSegundoNCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDireccionClie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoPCli = new javax.swing.JTextField();
        txtApellidoMCli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefonoClie = new javax.swing.JTextField();
        btnRegistrarCliente = new javax.swing.JButton();
        btnAgregarMascota = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DNI Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtDniClie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txtDniClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Primer nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtNombreClie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txtNombreClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 230, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Segundo nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        txtSegundoNCli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSegundoNCli.addActionListener(this::txtSegundoNCliActionPerformed);
        jPanel1.add(txtSegundoNCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 230, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Apellido materno");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Dirección cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        txtDireccionClie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDireccionClie.addActionListener(this::txtDireccionClieActionPerformed);
        jPanel1.add(txtDireccionClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 230, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Apellido paterno");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        txtApellidoPCli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txtApellidoPCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 230, 50));

        txtApellidoMCli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtApellidoMCli.addActionListener(this::txtApellidoMCliActionPerformed);
        jPanel1.add(txtApellidoMCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 230, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Telefono cliente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        txtTelefonoClie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txtTelefonoClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 230, 50));

        btnRegistrarCliente.setBackground(new java.awt.Color(255, 51, 0));
        btnRegistrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarCliente.setText("REGISTRAR CLIENTE");
        jPanel1.add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 230, 50));

        btnAgregarMascota.setBackground(new java.awt.Color(255, 0, 0));
        btnAgregarMascota.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregarMascota.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarMascota.setText("AGREGAR MASCOTA");
        jPanel1.add(btnAgregarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 230, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("Registrar Cliente");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSegundoNCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoNCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoNCliActionPerformed

    private void txtApellidoMCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMCliActionPerformed

    private void txtDireccionClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionClieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarMascota;
    public javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtApellidoMCli;
    public javax.swing.JTextField txtApellidoPCli;
    public javax.swing.JTextField txtDireccionClie;
    public javax.swing.JTextField txtDniClie;
    public javax.swing.JTextField txtNombreClie;
    public javax.swing.JTextField txtSegundoNCli;
    public javax.swing.JTextField txtTelefonoClie;
    // End of variables declaration//GEN-END:variables
}
