/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author pc
 */
public class frmrCancelarCita extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmrCancelarCitas
     */
    public frmrCancelarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCancelarCita = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidCita = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        btnCancelarCita = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCancelarCita.setBackground(new java.awt.Color(153, 51, 255));
        pnlCancelarCita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CANCELAR CITA");
        pnlCancelarCita.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 270, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID CITA");
        pnlCancelarCita.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        pnlCancelarCita.add(txtidCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 470, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ESTADO");
        pnlCancelarCita.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, 20));

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlCancelarCita.add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 470, 60));

        btnCancelarCita.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelarCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarCita.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarCita.setText("CANCELAR ");
        btnCancelarCita.addActionListener(this::btnCancelarCitaActionPerformed);
        pnlCancelarCita.add(btnCancelarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 470, 60));

        getContentPane().add(pnlCancelarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 520, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCita;
    public javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel pnlCancelarCita;
    public javax.swing.JTextField txtidCita;
    // End of variables declaration//GEN-END:variables
}
