/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author user
 */
public class frmTablaDeEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmTablaDeEmpleados
     */
    public frmTablaDeEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEmpleados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistrosEmpleados = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEmpleados.setBackground(new java.awt.Color(153, 153, 255));
        pnlEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRegistrosEmpleados.setBackground(new java.awt.Color(51, 102, 255));
        tblRegistrosEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblRegistrosEmpleados);

        pnlEmpleados.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 990, 560));

        getContentPane().add(pnlEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel pnlEmpleados;
    public javax.swing.JTable tblRegistrosEmpleados;
    // End of variables declaration//GEN-END:variables
}
